id: '1706126432721'
alias: Turn on overloop light after sunset
description: ''
trigger:
- event: sunset
  offset: '-1800'
  platform: sun
condition: []
action:
- data:
    brightness_pct: 20
  service: light.turn_on
  target:
    entity_id: light.overloop_lamp
