id: '1707054491472'
alias: Notify when robby is finished
description: ''
trigger:
- platform: state
  entity_id: vacuum.robby
  from: cleaning
  to: returning
condition: []
action:
- service: notify.mobile_app_iphone
  data:
    title: Robby is klaar!
    message: Robby is klaar met stofzuigen en probeert z'n dock te vinden.
- service: chime_tts.say
  data:
    chime_path: drumroll
    delay: 450
    tts_playback_speed: 100
    volume_level: 0.5
    message: Robby is klaar met stofzuigen!
    tts_platform: cloud
    language: nl-NL
    announce: true
  target:
    entity_id: media_player.speaker
mode: single
