id: '1705919941116'
alias: Notify us when doorbell rings
description: ''
trigger:
- entity_id:
  - binary_sensor.amcrest_ad410_doorbell
  from: 'off'
  platform: state
  to: 'on'
  id: doorbell_pressed
condition: []
action:
- parallel:
  - service: rflink.send_command
    data:
      device_id: newkaku_011c0226_0
      command: ALLON
  - service: chime_tts.say
    target:
      entity_id: media_player.speaker
    data:
      chime_path: ding_dong
      offset: 450
      final_delay: 0
      tts_playback_speed: 100
      volume_level: 0.5
      language: nl-NL
      announce: false
      message: Er staat iemand aan de deur. Doe snel open!
  - if:
    - condition: trigger
      id: doorbell_pressed
    then:
    - service: camera.snapshot
      data:
        filename: /config/www/snapshots/doorbell/latest.jpg
      target:
        entity_id:
        - camera.doorbell
    - service: notify.notify_us
      data:
        message: Er staat iemand aan de deur!
        data:
          attachment:
            url: /local/snapshots/doorbell/latest.jpg
            content_type: JPEG
