id: '1707383022760'
alias: 'iOS action: naar huis'
description: ''
triggers:
- event_type: ios.action_fired
  event_data:
    actionName: Naar huis
  trigger: event
conditions: []
actions:
- action: input_boolean.toggle
  metadata: {}
  data: {}
  target:
    entity_id: input_boolean.driving_home
- metadata: {}
  data:
    chime_path: dun_dun_dun
    end_chime_path: ''
    offset: 450
    final_delay: 0
    tts_playback_speed: 100
    message: Papa is onderweg naar zijn schatjes! Hoe lang het nog duurt krijg je
      binnenkort ook te horen.
    tts_platform: cloud
    announce: true
    language: nl-NL
  target:
    entity_id: media_player.speaker
  action: chime_tts.say
mode: single
