id: '1707054447663'
alias: Notify us when washing machine is finished
description: ''
trigger:
- entity_id:
  - binary_sensor.washingmachine
  platform: state
  to: 'off'
  from: 'on'
condition: []
action:
- service: notify.notify_us
  data:
    message: Snel leeghalen!
    title: De wasmachine is klaar
- service: chime_tts.say
  data:
    chime_path: mp3_path_placeholder-tada
    delay: 450
    tts_playback_speed: 100
    volume_level: 0.5
    message: De wasmachine is klaar!
    tts_platform: cloud
    language: nl-NL
    announce: true
  target:
    entity_id: media_player.speaker
mode: single
