id: '1706556268392'
alias: Livingroom lights on just before sunset
description: ''
trigger:
- event: sunset
  offset: '-1800'
  platform: sun
condition: []
action:
- service: light.turn_on
  data: {}
  target:
    entity_id:
    - light.eettafel_lamp
    - light.woonkamer_lampen
- service: scene.turn_on
  target:
    entity_id: scene.living_room_default
  metadata: {}
mode: single
