id: '1706556536535'
alias: Turn off lights during day
description: ''
trigger:
- event: sunrise
  offset: '1815'
  platform: sun
condition: []
action:
- data:
    transition: 120
  service: light.turn_off
  target:
    entity_id:
    - light.overloop_lamp
    - light.woonkamer_lampen
    - light.eettafel_lamp
    - light.slaapkamer_lamp
