id: '1707055017934'
alias: Update energy tariffs
description: ''
trigger:
- platform: template
  value_template: '{{ now().day == 1 and states(''sensor.time'') == "00:00" }}'
condition: []
action:
- service: input_text.set_value
  data:
    value: '1.22505'
  target:
    entity_id:
    - input_text.actual_gas_tariff
- service: input_text.set_value
  data:
    value: '0.31656'
  target:
    entity_id: input_text.actual_electricity_tariff_high
- service: input_text.set_value
  data:
    value: '0.32866'
  target:
    entity_id: input_text.actual_electricity_tariff_low
mode: single
